const text = {
  REQUIRED_SLUG: 'Slug er påkrevd',
  REQUIRED_NAME: 'Navn er påkrevd',
  REQUIRED_TAGNAME: 'Tagnavn er påkrevd',
  REQUIRED_TITLE: 'Tittel er påkrevd',
  REQUIRED_RICHTEXT: 'Riktekst er påkrevd',
  REQUIRED_PREAMBLE: 'Ingress er påkrevd',
  REQUIRED_OPENING_HOUR: 'Åpningstid er påkrevd',
  REQUIRED_IMAGE: 'Bilde er påkrevd',
  REQUIRED_VIDEO: 'Video er påkrevd',
  REQUIRED_FORM: 'Skjema er påkrevd',
  REQUIRED_DEALER: 'Forhandler er påkrevd',
  REQUIRED_DATE: 'Dato er påkrevd',
  REQUIRED_CUSTOMER_BENEFIT_STANDARD: 'Standard kundefordel er påkrevd',
  REQUIRED_CTA: 'CTA er påkrevd',
  REQUIRED_CARBRAND: 'Bilmerke er påkrevd',
  REQUIRED_MODEL: 'Bilmodell er påkrevd',
  REQUIRED_MODEL_INFO: 'Modell informasjon er påkrevd',
  REQUIRED_URL: 'En gyldig URL er påkrevd',
  REQUIRED_PRODUCT_NAME: 'Produktnavn er påkrevd',
  REQUIRED_PRICE: 'Pris er påkrevd',
  REQUIRED_DEALER_ID: 'Forhandler-ID er påkrevd',
  INVALID_DEALER_ID: 'Ugyldig forhandler-ID',
  REQUIRED_PHONE: 'Telefonnummer er påkrevd',
  INVALID_PHONE: 'Telefonnummer er ugyldig',
  REQUIRED_EMAIL: 'E-postadresse er påkrevd',
  INVALID_EMAIL: 'E-postadressen er ugyldig',
  REQUIRED_ADDRESS: 'Adresse er påkrevd',
  REQUIRED_POST_CODE: 'Postnummer er påkrevd',
  REQUIRED_POST_LOCATION: 'Poststed er påkrevd',
  INVALID_POST_CODE: 'Postnummer er ugyldig',
  REQUIRED_DATETIME_START: 'Starttidspunkt er påkrevd',
  REQUIRED_DATETIME_END: 'Slutttidspunkt er påkrevd',
  REQUIRED_CAMPAIGN_SINGULAR: 'Minst én enkelt kampanjekategori er påkrevd',
  REQUIRED_CAMPAIGN_DISCOUNT: 'Kampanjetilbud er påkrevd',
  REQUIRED_FIELD_VALUE: 'Feltet må fylles ut',
  INVALID_RANGE_0_100: 'Prosent må være et tall mellom 0 og 100',
  INVALID_NUMERIC: 'Kan kun inneholde tall',
  INVALID_PARENT: 'Valgt "Overordnet side for URL" finnes allerede i url-stien',
  REQUIRED_ATLEAST_1: 'Må inneholde minst et objekt',
  WARN_NO_SELECTION_SCHEMA: 'Teksten vil ikke bli vist uten at skjema er valgt',
  WARN_ICON_SELECTED: 'Teksten vil ikke bli vist når burger-ikon er valgt',
  LIMIT_MENU: 'Maks 5 menypunkter',
  LIMIT_PARENT: 'Maks nivå nådd',
  REQUIRED_ENTRY: 'Alle elementer må inneholde lenketekst og inngangstype',
  REQUIRED_CONTENT_TYPE: 'Alle elementer må inneholde en innholdstype',
  REQUIRED_REFERENCE: 'Alle elementer må ha en referanse',
  SEO_TRUNCATE: 'Lengre tekster kan bli avkortet av søkemotorer',
};

export default text;
