const schemas = {
	GENERAL_SETTINGS: 'generalSettings',
	REDIRECT: 'redirect',
	SEO_SETTINGS: 'seoSettings',
	SOCIAL_MEDIA_SETTINGS: 'socialMediaSettings',
	COOKIE_SETTINGS: 'cookieSettings',
	TAG: 'tag',
	TAG_CATEGORY: 'tagCategory',
	FOOTER: 'footer',
	MENU: 'menu',
	TAGS_DISCIPLINE: 'educationLevelTags',
	TAGS_RESOURCE_FORMAT: 'resourceFormatTags',
	TAGS_REPORT_TYPE: 'reportTypeTags',
	CROSS_AREA: 'crossArea',
	DISCIPLINE: 'discipline',
	EDITOR_TOPIC: 'editorTopic',
	HOME_PAGE: 'homepage',
	NEWS_ARTICLE: 'newsArticle',
	INFORMATION_ARTICLE: 'informationArticle',
	REPORT: 'report',
	CONTACT: 'contact',
	WARNING: 'warningText',
	FACT_BOX: 'factBox',
	STANDARD_TEXT: 'standardText',
	VIDEO: 'video',
	NEWS: 'newsArticle',
	GRANTS: 'grant',
	EVENTS: 'event',
	PROJECTS: 'project',
	PROGRAMS: 'program',
	REPORTS: 'report',
	RESEARCH: 'research',
	RESOURCES: 'resource',
	PROFESSION: 'profession',
	APPROVAL_BODY: 'approvalBody',
	WRAPPER_PAGE: 'wrapperPage',
	EPLUSS_HOME_PAGE: 'ePlussHomepage',
	FR_HOME_PAGE: 'frHomepage',
	ALIAS: 'alias',
	PASSWORD_PROTECTED: 'passwordProtectedPage',
}

export const krSchemas = {
	ALERT: 'kr_alert',
	EVENT: 'kr_event',
	FACT_BOX: 'kr_factBox',
	FILE: 'kr_file',
	INFORMATION_ARTICLE: 'kr_informationArticle',
	MEETING: 'kr_meeting',
	NAVIGATION_PAGE: 'kr_navigationpage',
	NEWS_ARTICLE: 'kr_newsArticle',
	PERSON: 'kr_person',
	PROCESS: 'kr_process',
	VIDEO: 'kr_video',
	EVENT_PROGRAM: 'kr_eventProgram',
	FIND_JOURNALS: 'kr_findJournals',
	IMAGE: 'kr_imageWithAlt',
	LINK: 'kr_link',
	LINK_ENTRY: 'kr_linkEntry',
	LINK_ENTRY_MORE: 'kr_linkEntryMore',
	LINK_FEATURED: 'kr_linkFeatured',
	PUBLISHING_DECISIONS: 'kr_publishingDecisions',
	SOCIAL_MEDIA: 'kr_socialMedia',
	STATISTICS: 'kr_statistics',
	SUGGEST_CHANNEL: 'kr_suggestChannel',

	// Singletons
	HOME_PAGE: {
		kr: 'kr_homepage',
		erih: 'erih_homepage',
	},
	FOOTER: {
		kr: 'kr_footer',
		erih: 'erih_footer',
	},
	MENU: {
		kr: 'kr_menu',
		erih: 'erih_menu',
	},
	LOGIN: {
		kr: 'kr_login',
		erih: 'erih_login',
	},
	SIGNUP: {
		kr: 'kr_signup',
		erih: 'kr_signup',
	},
	MYPAGE: {
		kr: 'kr_myPage',
		erih: 'kr_myPage',
	},
	MY_SUGGESTIONS_PAGE: {
		kr: 'kr_mySuggestionsPage',
		erih: 'kr_mySuggestionsPage',
	},
	SUGGEST_CHANNEL_PAGE: {
		kr: 'kr_suggestChannelPage',
		erih: 'erih_submitJournal',
	},
}

export default schemas
